T2V_Bee/Web_ecomic/Controllers/XuliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_ecomic.Models;

namespace Web_ecomic.Controllers
{
    public class XuliController : Controller
    {
        //
        // GET: /Xuli/
        private EcommicEntities3 db = new EcommicEntities3();
        public static List<Chitietphieu> gioHang = new List<Chitietphieu>();
        public ActionResult Xulidanhsachloaisanpham(int Idloai)
        {
            var danhsach = db.Sanphams.Where(m => m.ID_Loai == Idloai).ToList();
            ViewBag.run = 1;
            return View("Xulidanhsachloaisanpham",danhsach);
        }
        [HttpGet]
        public ActionResult AddToCart(string color, string quality)
        {
            try
            {
                int soluong = Int32.Parse(quality);
                if (soluong == 0)
                    soluong = 1;
                int temp = getctgiohang((int)T2V_Controller.current_sanpham.ID);
                if (temp == -1)
                {
                    Chitietphieu chitiet = new Chitietphieu();
                    chitiet.ID_sanpham = T2V_Controller.current_sanpham.ID;
                    chitiet.Soluong = soluong;
                    chitiet.color = color;
                    chitiet.Dongia = soluong * T2V_Controller.current_sanpham.Giatien;
                    chitiet.Sanpham = T2V_Controller.current_sanpham;
                    gioHang.Add(chitiet);
                }
                else
                {
                    if ((gioHang[temp].Soluong + soluong) <= T2V_Controller.current_sanpham.Soluong)
                    {
                        gioHang[temp].Soluong += soluong;
                        gioHang[temp].Dongia = gioHang[temp].Soluong * T2V_Controller.current_sanpham.Giatien;
                    }
                }
            }
            catch (Exception e) { }
            return RedirectToAction("Index", "T2V_");
        }
        public int getctgiohang(int a)
        {
            for(int i = 0 ; i < gioHang.Count ; i++)
            {
                if (gioHang[i].ID_sanpham == a)
                    return i;
            }
            return -1;
        }
        [HttpPost]
        public ActionResult Loaikhoigiohang(int a)
        {
            gioHang.RemoveAt(a);
            Session["tongtien"] = gioHang.Sum(m => m.Dongia).ToString();
            Session["soluong"] = gioHang.Sum(m => m.Soluong).ToString();
            Session["giohang"] = gioHang.Count;
            return View(gioHang);
        }
        [HttpPost]
        public ActionResult ChangeQuanity(string a, int b)
        {
            try
            {
                gioHang[b].Soluong = Int32.Parse(a);
                gioHang[b].Dongia = Int32.Parse(a) * gioHang[b].Sanpham.Giatien;
                Session["tongtien"] = XuliController.gioHang.Sum(m => m.Dongia).ToString();
                Session["soluong"] = XuliController.gioHang.Sum(m => m.Soluong).ToString();
            }
            catch (Exception e) { }
            return View("Loaikhoigiohang", gioHang);
        }
        [HttpPost]
        public JsonResult Changecolor(string a, int b)
        {
            try
            {
                gioHang[b].color = a;
            }
            catch (Exception e) { }
            return Json("changecolor", JsonRequestBehavior.AllowGet);
        }
        public ActionResult Deleteall()
        {
            gioHang.Clear();
            Session["tongtien"] = 0;
            Session["soluong"] = 0;
            Session["giohang"] = 0;
            return View("Loaikhoigiohang", gioHang);
        }
        public ActionResult Formthanhtoan()
        {
            return View(new Nguoinhan());
        }
        [HttpPost]
        public ActionResult Thanhtoan(Nguoinhan a, string ghichu)
        {
            
            try
            {
                if (gioHang.Count == 0)
                {
                    return RedirectToAction("Quanligiohang", "T2V_");
                }
                // save nguoi nhan
                db.Nguoinhans.Add(a);
                db.SaveChanges();
                int IDnguoinhan = a.ID;
                int IDnguoimua = T2V_Controller.Current_accounts.ID;
                Phieudathang phieu = new Phieudathang();
                phieu.Ghichu = ghichu;
                phieu.Trangthai = 1;
                phieu.Nguoinhan = IDnguoinhan;
                phieu.Nguoimua = IDnguoimua;
                phieu.Ngaymua = DateTime.Now;
                phieu.Soluong = gioHang.Count();
                phieu.Tongtien = gioHang.Sum(m => m.Dongia);
                db.Phieudathangs.Add(phieu);
                db.SaveChanges();
                int IDphieu = phieu.ID;
                for(int i = 0 ; i < gioHang.Count ; i++)
                {
                    gioHang[i].ID_phieu = IDphieu;
                    gioHang[i].Sanpham = null;
                    db.Chitietphieux.Add(gioHang[i]);
                }
                db.SaveChanges();
                gioHang.Clear();
            }
            catch (Exception e) { 
                ModelState.AddModelError("", "Da bi loi");
                return RedirectToAction("Quanligiohang", "T2V_");
            }
            return RedirectToAction("Index", "T2V_");
        }
        [HttpPost]
        public JsonResult Addtocart(int ID)
        {
            try
            {
                var temp1 = db.Sanphams.Where(m => m.ID == ID).ToList();
                int temp = getctgiohang(ID);
                if (temp == -1)
                {
                    Chitietphieu chitiet = new Chitietphieu();
                    chitiet.ID_sanpham = ID;
                    chitiet.Soluong = 1;
                    chitiet.color = "Trắng";
                    chitiet.Dongia = temp1[0].Giatien;
                    chitiet.Sanpham = temp1[0];
                    gioHang.Add(chitiet);
                }
                else
                {
                    if ((gioHang[temp].Soluong + 1) <= temp1[0].Soluong)
                    {
                        gioHang[temp].Soluong += 1;
                        gioHang[temp].Dongia = gioHang[temp].Soluong * temp1[0].Giatien;
                    }
                }
            }
            catch (Exception e) { }
            return Json(gioHang.Count,JsonRequestBehavior.AllowGet);
        }
        
    }
}

T2V_Bee/Web_ecomic/Views/Xuli/Formthanhtoan.cshtml
@model Web_ecomic.Models.Nguoinhan
@{
    Layout = null;
    <link href="~/css/Style_tintuc.css" rel="stylesheet" />
    <script src="@Url.Content("~/js/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/jqueryval")
}
@using (Html.BeginForm("Thanhtoan","Xuli",FormMethod.Post))
{
    <ul id="tt_nn">
        <li>
            <div id="title_nn">
                <h2>Thông tin đặt hàng</h2>
            </div>
        </li>
        <li>
            <label class="form-label">Họ và Tên * :</label>
            <div class="hoten_nn">
                @Html.TextBoxFor(m=>m.Hoten)
                @Html.ValidationMessageFor(m=>m.Hoten)
            </div>
        </li>
        <li>
            <label class="form-label">SDT * :</label>
            <div class="sdt_nn">
                @Html.TextBoxFor(m=>m.SDT)
                @Html.ValidationMessageFor(m=>m.SDT)
            </div>
        </li>
        <li>
            <label class="form-label">Địa chỉ *</label>
            <div class="diachi_nn">
                @Html.TextBoxFor(m=>m.Diachi)
                @Html.ValidationMessageFor(m=>m.Diachi)
            </div>
        </li>
        <li>
            <label class="form-label">Ghi chú</label>
            <textarea name="ghichu"></textarea>
        </li>
        <li>
            <div class="form-button">
                <button type="submit" class="thanhtoan_nn">Thanh Toán</button>
            </div>
        </li>
    </ul>
}

T2V_Bee/Web_ecomic/Views/Xuli/Loaikhoigiohang.cshtml
@model List<Web_ecomic.Models.Chitietphieu>
@{
    Layout = null;
    <link href="~/css/Style_tintuc.css" rel="stylesheet" />
}

    <div class="simpleCart_items">
        @for (int i = 0; i < @Model.Count; i++)
        {
            <div class="itemContainer">
                <div class="itemname">@Model[i].Sanpham.TenSanPham</div>
                <div class="itemthumb">
                    <img src="../../@Model[i].Sanpham.Duongdanhinh" alt="img" />
                </div>
                <div class="itemQuantity">
                    <select onchange="changequantity(this.value,@i);">
                        @for (int j = 1; j <= @Model[i].Sanpham.Soluong; j++)
                        {
                            if (j == Model[i].Soluong)
                            {
                                <option value="@j" selected>@j</option>
                            }
                            else
                            {
                                <option value="@j">@j</option>
                            }
                        }
                    </select>

                </div>
                <div class="itemcolor">
                    Color :
                    <select onchange="changecolor(this.value,@i);">
                        @for (int j = 0; j < @Model[i].Sanpham.Colors.Count; j++)
                        {
                            if (Model[i].Sanpham.Colors.ToList()[j].Ten == Model[i].color)
                            {
                                <option value="@Model[i].Sanpham.Colors.ToList()[j].Ten" selected>@Model[i].Sanpham.Colors.ToList()[j].Ten</option>
                            }
                            else
                            {
                                <option value="@Model[i].Sanpham.Colors.ToList()[j].Ten">@Model[i].Sanpham.Colors.ToList()[j].Ten</option>
                            }
                        }
                    </select>
                </div>
                <div class="itemTotal">
                    VND : @Model[i].Dongia
                </div>
                <div class="itemremove">
                    <a href="javascript:;" onclick="javacript:Loaibo(@i);">Loại bỏ</a>
                </div>
            </div>
        }
        <div class="clear"></div>
        <div class="mycartinfo">
            <table>
                <tbody>
                    <tr><td class="title">Số lượng: </td><td class="numb"><span class="simpleCart_quantity">@Session["soluong"]</span></td></tr>
                    <tr><td class="title">Thành tiền: </td><td class="numb"><span class="simpleCart_total">VND&nbsp;@Session["tongtien"]</span></td></tr>
                    <tr><td class="title">Phí ship: </td><td class="numb"><span class="simpleCart_shippingCost">VND&nbsp;0.00</span></td></tr>
                    <tr><td class="title">Tổng cộng: </td><td class="numb"><span class="simpleCart_finalTotal">VND&nbsp;@Session["tongtien"]</span></td></tr>
                </tbody>
            </table>
            <div class="clear"></div>
            <div class="button_check">
                <a class="simpleCart_empty" href="javascript:;" onclick="Deleteall();" title="Xóa hết đơn hàng">Xóa hết</a>
                <a class="thanhtoan" href="javascript:;" onclick="Thanhtoanform();">Thanh toán</a>
            </div>
            <div class="clear"></div>
        </div>
    </div>

<script type="text/javascript">
    $(function () {
        $('.last').html(@Session["giohang"]);
    })
</script>

T2V_Bee/Web_ecomic/Views/Xuli/Xulidanhsachloaisanpham.cshtml
@model List<Web_ecomic.Models.Sanpham>
@{
    Layout = null;
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="@Url.Content("~/js/jquery.min.js")"></script>
    <!-- Custom Theme files -->
    <link href="@Url.Content("~/css/style.css")" rel="stylesheet" type="text/css" media="all" />
    <script src="~/js/jquery.flexisel.js"></script>

    <link rel="stylesheet" href="@Url.Content("~/css/flexslider.css")" type="text/css" media="screen" />
    if (ViewBag.run != null)
    {
    <script type="text/javascript">
        $(function () {
            $("#flexiselDemo").flexisel({
                visibleItems: 4,
                animationSpeed: 1000,
                autoPlay: true,
                autoPlaySpeed: 3000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 3
                    }
                }
            });

        });
    </script>
    }
}
<div class="course_demo">
    <ul id="flexiselDemo">
        @for (int i = 0; i < 4; i++)
        {
            <li>
                <div class="ipad text-center">
                    <a href="@Url.Action("Thongtinchitietsanpham","T2V_", @Model[i])"><img src="@Model[i].Duongdanhinh" alt="" /></a>
                    <h4>@Model[i].TenSanPham</h4>
                    <h3>$@Model[i].Giatien</h3>
                    <ul>
                        <li><i class="cart-1"></i></li>
                        <li><a class="cart" href="#">Thêm vào giỏ</a></li>
                    </ul>
                    <div class="clearfix"></div>
                    <ul>
                        <li><i class="heart"></i></li>
                        <li><a class="cart" href="#">SP yêu thích</a></li>
                    </ul>
                </div>
            </li>
        }
    </ul>
</div>