T2V_Bee/Web_ecomic/Models/Chitietphieu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ecomic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietphieu
    {
        public int ID { get; set; }
        public Nullable<int> ID_sanpham { get; set; }
        public Nullable<int> ID_phieu { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Dongia { get; set; }
        public string color { get; set; }
    
        public virtual Phieudathang Phieudathang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}

T2V_Bee/Web_ecomic/Models/Comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ecomic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> ID_loai { get; set; }
        public Nullable<int> ID_Sanpham { get; set; }
        public string Name { get; set; }
        public string Url_image { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
        public virtual Tintuc Tintuc { get; set; }
    }
}

T2V_Bee/Web_ecomic/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ecomic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Submenus = new HashSet<Submenu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Submenu> Submenus { get; set; }
    }
}

T2V_Bee/Web_ecomic/Models/Sanpham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ecomic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public Sanpham()
        {
            this.Comments = new HashSet<Comment>();
            this.HinhMotas = new HashSet<HinhMota>();
            this.Chitietphieux = new HashSet<Chitietphieu>();
            this.Colors = new HashSet<Color>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string Duongdanhinh { get; set; }
        public Nullable<double> Giatien { get; set; }
        public string Motasanpham { get; set; }
        public Nullable<int> ID_Loai { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string NSX { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<HinhMota> HinhMotas { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual ICollection<Chitietphieu> Chitietphieux { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
    }
}

T2V_Bee/Web_ecomic/Controllers/T2V_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Web_ecomic.Models;
using PagedList;
using System.Data.Entity;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Owin.Host.SystemWeb;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using System.Drawing;
using System.Drawing.Text;
using System.Drawing.Drawing2D;
using System.Text;

namespace Web_ecomic.Controllers
{
    public class T2V_Controller : Controller
    {
        //
        // GET: /T2V_/
        public static WebModel data = null;
        private static WebModel datads = new WebModel(); 
        public static int CurrentID = 6;
        private EcommicEntities3 db = new EcommicEntities3();
        private static int id_Current;
        private static Comment cm;
        public static TaiKhoan Current_accounts;
        public static Sanpham current_sanpham;

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationSignInManager _signInManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }

        public ActionResult Index()
        {
            if(Request.IsAuthenticated)
            {
                try
                {
                    Current_accounts = db.TaiKhoans.Where(m => m.Tentaikhoan == User.Identity.Name).ToList()[0];
                }
                catch (Exception e) { Current_accounts = new TaiKhoan(); }
            }
            if (data == null)
            {
                data = new WebModel();
                LoadData();

            }
            data.Tintucmoi = db.Tintucs.OrderByDescending(m => m.Ngay).Take(3).ToList();
            data.DSSanpham = db.Sanphams.ToList();
            data.sanPhamMoi = data.DSSanpham.OrderByDescending(m => m.Ngaydang).Take(3).ToList();
            data.DbLoaisanpham = db.LoaiSanPhams.ToList();

            Session["newproduct"] = data.DSSanpham.OrderByDescending(m => m.Ngaydang).Take(2).ToList();
            Session["menu"] = LoadMenu();
            
            Session.Add("giohang", XuliController.gioHang.Count);
            return View(data);
        }
        public List<Menupage> LoadMenu()
        {
            List<Menupage> ds = new List<Menupage>();
            int a;
            var menu = db.Menus.ToList();
            for(int i = 0 ; i < menu.Count ; i++)
            {
                Menupage temp = new Menupage();
                temp.ID = menu[i].ID;
                temp.Name = menu[i].Name;
                temp.Ds = db.Submenus.Where(m => m.Id_menu == temp.ID).ToList();
                ds.Add(temp);
            }
            return ds;
        }
        public void LoadData()
        {
            data.Slider.Add("images/slide1.jpg");
            data.Slider.Add("images/slide2.jpg");
            data.Slider.Add("images/slide3.jpg");
            data.Slider.Add("images/slide4.jpg");
            data.Slider.Add("images/slide5.jpg");
            data.Slider.Add("images/slide6.jpg");

            /*data.sanPhamMoi.Add(new SanPham(0, "Iphone6", "images/m1.jpg", 10, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip63.jpg", "../../images/Ip6/ip64.jpg" }));
            data.sanPhamMoi.Add(new SanPham(1, "MacBook Pro", "images/m2.jpg", 30, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/m1.jpg", "../../images/Macbook/macbook1.jpg", "../../images/Macbook/macbook2.jpg" }));
            data.sanPhamMoi.Add(new SanPham(2, "Zenfone 2", "images/m4.jpg", 10, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/m1.jpg", "s" }));

            data.SanphamShop.Add(new SanPham(3, "Ipad II", "images/a1.jpg", 10, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/Ip6/ip61.jpg", "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip63.jpg", "../../images/Ip6/ip64.jpg" }));
            data.SanphamShop.Add(new SanPham(4, "Ipad Mini", "images/a2.jpg", 6, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/Ip6/ip61.jpg", "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip63.jpg", "../../images/Ip6/ip64.jpg" }));
            data.SanphamShop.Add(new SanPham(5, "Iphone6 plus", "images/a4.jpg", 10, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/Ip6/ip61.jpg", "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip63.jpg", "../../images/Ip6/ip64.jpg" }));
            data.SanphamShop.Add(new SanPham(6, "MacBook Air", "images/a5.jpg", 25, "Thong tin chi tiết sản phẩm", new List<string> { "../../images/Ip6/ip61.jpg", "../../images/Ip6/ip62.jpg", "../../images/Ip6/ip63.jpg", "../../images/Ip6/ip64.jpg" }));
            */
            
        }

        public ActionResult Thongtinnhom()
        {
            return View();
        }

        public ActionResult SanPham()
        {
            DocDanhSachSanPham();
            return View(data);
        }

        private static List<Sanpham> gt = new List<Sanpham>();
        public ActionResult Danhsachsanpham(string name, string sapxep, int? page, string submenu)
        {
            if(name == "Tin tức")
            {
                return RedirectToAction("Danhsachtintuc");
            }
            bool temp = false;
            if (datads.isSort == false && (sapxep != null && datads.Sapxep != sapxep))
            {
                temp = true;
            }
            if (datads.isSort == false)
            {
                if (name != null)
                    datads.Loaisanpham = name;
                if (sapxep != null)
                    datads.Sapxep = sapxep;
                if (name == "Sản phẩm")
                {
                    if (datads.Sapxep == "Giá giảm")
                        gt = gt.OrderByDescending(n => n.Giatien).ToList();
                    else
                        if (datads.Sapxep == "Giá tăng")
                            gt = gt.OrderBy(n => n.Giatien).ToList();
                        else
                            gt = db.Sanphams.ToList();
                }
                else
                {
                    //data.DbLoaisanpham = db.LoaiSanPhams.Where(n => n.TenLoai == data.Loaisanpham).ToList();
                    int id = 0;
                    if (datads.Loaisanpham != "tk" && datads.Loaisanpham != null)
                    {
                        var tam = db.LoaiSanPhams.Where(n => n.TenLoai == datads.Loaisanpham).ToList();
                        if(tam.Count >= 1)
                            id = tam[0].ID;
                    }
                    if (datads.Sapxep == "Giá giảm")
                        gt = gt.OrderByDescending(n => n.Giatien).ToList();
                    else
                    {
                        if (datads.Sapxep == "Giá tăng")
                            gt = gt.OrderBy(n => n.Giatien).ToList();
                        else
                        {
                            if (datads.Loaisanpham == "tk")
                            { }
                            else
                            {
                                if (submenu != null)
                                {
                                    gt = db.Sanphams.Where(m => m.ID_Loai == id && m.NSX == submenu).ToList();
                                }
                                else
                                    gt = db.Sanphams.Where(n => n.ID_Loai == id).ToList();
                            }
                        }
                    }
                }
            }
            else
            {
                if (name == "Sản phẩm")
                {
                    if (datads.Sapxep == "Giá giảm")
                        gt = gt.OrderByDescending(n => n.Giatien).ToList();
                    else
                    {
                        if (datads.Sapxep == "Giá tăng")
                            gt = gt.OrderBy(n => n.Giatien).ToList();
                        else
                        {
                            if (datads.Sapxep == "Giá tăng")
                                gt = gt.OrderBy(n => n.Giatien).ToList();
                            else
                                gt = db.Sanphams.ToList();
                        }
                    }
                }
                else
                {
                    // data.DbLoaisanpham = db.LoaiSanPhams.Where(n => n.TenLoai == data.Loaisanpham).ToList();
                    int id = 0;
                    if (datads.Loaisanpham != "tk" && datads.Loaisanpham != null)
                    {
                        var tam = db.LoaiSanPhams.Where(n => n.TenLoai == datads.Loaisanpham).ToList();
                        if (tam.Count >= 1)
                            id = tam[0].ID;
                    }
                    if (datads.Sapxep == "Giá giảm")
                        gt = gt.OrderByDescending(n => n.Giatien).ToList();
                    else
                        if (datads.Sapxep == "Giá tăng")
                            gt = gt.OrderBy(n => n.Giatien).ToList();
                        else
                        {
                            if (datads.Loaisanpham == "tk")
                            { }
                            else
                            {
                                if (submenu != null)
                                {

T2V_Bee/Web_ecomic/Views/T2V_/ChangePassword.cshtml
@model Web_ecomic.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "Thaydoimatkhau";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/css/Style_tintuc.css" rel="stylesheet" />
}

<body>
    <!-- start main -->
    <div class="main_bg">
        <div class="main">
            <!-- start span1_of_1 -->
            <div class="left_content">
                @using (Html.BeginForm("ChangePassword", "T2V_", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <h4>Change your password.</h4>
                    <hr />
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.OldPassword, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-default" value="Change" />
                        </div>
                    </div>
                }
            </div>


            <div class="sub-cate single-subcate">
                <div class=" top-nav rsidebar span_1_of_left">
                    <h3 class="cate">CATEGORIES</h3>
                    <ul class="menu">
                        <li>
                            <ul class="kid-menu ">
                                <li><a href="@Url.Action("Thongtincanhan","T2V_")">Xem thông tin cá nhân</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--initiate accordion-->
                <script type="text/javascript">
                    $(function () {
                        var menu_ul = $('.menu > li > ul'),
                               menu_a = $('.menu > li > a');
                        menu_ul.hide();
                        menu_a.click(function (e) {
                            e.preventDefault();
                            if (!$(this).hasClass('active')) {
                                menu_a.removeClass('active');
                                menu_ul.filter(':visible').slideUp('normal');
                                $(this).addClass('active').next().stop(true, true).slideDown('normal');
                            } else {
                                $(this).removeClass('active');
                                $(this).next().stop(true, true).slideUp('normal');
                            }
                        });

                    });
                </script>
                @if (@Session["newproduct"] != null)
                {
                    @Html.Partial("sanphamquancao", @Session["newproduct"])
                }
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- Modal -->
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>

T2V_Bee/Web_ecomic/Views/T2V_/Chinhsuattcanhan.cshtml
@model Web_ecomic.Models.TaiKhoan
@{
    ViewBag.Title = "Chinhsuattcanhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> li = new List<SelectListItem>();
    li.Add(new SelectListItem { Text = "Nam", Value = "0" });
    li.Add(new SelectListItem { Text = "Nữ", Value = "1" });
    ViewData["gioitinh"] = li;
}
<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link href="@Url.Content("~/css/Style_tintuc.css")" rel="stylesheet" type="text/css" />
<body>
    <!-- start main -->
    <div class="main_bg">
        <div class="main">
            <!-- start span1_of_1 -->
            <div class="left_content">
                <div class="infor">
                    @using (Html.BeginForm("Chinhsuattcanhan", "T2V_", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <fieldset>
                            <legend>Chỉnh sửa thông tin cá nhân :</legend>
                            <div>
                                @Html.HiddenFor(m => m.ID)
                                @Html.HiddenFor(m => m.Ngaydangki)
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconuse"></em>
                                    Tên tài khoản:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Tentaikhoan, new { @readonly = true })</p>
                                <p>@Html.ValidationMessageFor(m => m.Tentaikhoan)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconpass"></em>
                                    Pass:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Matkhau, new { @readonly = true })</p>
                                <p>@Html.ValidationMessageFor(m => m.Matkhau)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconame"></em>
                                    Họ và tên:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Hoten)</p>
                                <p>@Html.ValidationMessageFor(m=> m.Hoten)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconsex"></em>
                                    Giới tính:
                                </span>
                                
                                <p>@Html.DropDownListFor(m => m.Gioitinh, ViewData["gioitinh"] as List<SelectListItem>, "Please select a gender", new { style = "width:100px", @class = "dropdown1" })</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconimage"></em>
                                    Ảnh đại diện:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Imagedaidien, new { @id = "urlImage" })</p>
                                <p><input type="file" name="file" id="file" onchange="layurl(this.value)"></p>
                            </div>
         
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf icodate"></em>
                                    Ngày sinh:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Namsinh, new { id = "news_date" })</p>
                                <p>@Html.ValidationMessageFor(m=>m.Namsinh)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconwrite"></em>
                                    Email:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Email)</p>
                                <p>@Html.ValidationMessageFor(m=>m.Email)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconsdt"></em>
                                    Số điện thoại:
                                </span>
                                <p>@Html.TextBoxFor(m => m.SDT)</p>
                                <p>@Html.ValidationMessageFor(m=>m.SDT)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <em class="zmsprt zmiconopf iconame"></em>
                                    Địa chỉ:
                                </span>
                                <p>@Html.TextBoxFor(m => m.Diachi)</p>
                                <p>@Html.ValidationMessageFor(m=>m.Diachi)</p>
                            </div>
                            <div class="row-line">
                                <span class="ltinfouser">
                                    <input type="submit" value="chỉnh sửa" />
                                </span>
                            </div>
                        </fieldset>
                    }
                </div>
                </div>

            <div class="sub-cate single-subcate">
                <div class=" top-nav rsidebar span_1_of_left">
                    <h3 class="cate">CATEGORIES</h3>
                    <ul class="menu">
                        <li>
                            <ul class="kid-menu ">
                                <li><a href="@Url.Action("Thongtincanhan","T2V_")">Xem thông tin cá nhân</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!--initiate accordion-->
                <script type="text/javascript">
                    $(function () {
                        var menu_ul = $('.menu > li > ul'),
                               menu_a = $('.menu > li > a');
                        menu_ul.hide();
                        menu_a.click(function (e) {
                            e.preventDefault();
                            if (!$(this).hasClass('active')) {
                                menu_a.removeClass('active');
                                menu_ul.filter(':visible').slideUp('normal');
                                $(this).addClass('active').next().stop(true, true).slideDown('normal');
                            } else {
                                $(this).removeClass('active');
                                $(this).next().stop(true, true).slideUp('normal');
                            }
                        });

                    });
                </script>
                @if (@Session["newproduct"] != null)
                {
                    @Html.Partial("sanphamquancao", @Session["newproduct"])
                }
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- Modal -->
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $(function () {
        $("#news_date").datepicker();
    });
</script>
<script type="text/javascript">
    function layurl(url) {
        $("#urlImage").val(url);
    }
</script>

T2V_Bee/Web_ecomic/Views/T2V_/FormDangKi.cshtml
@model Web_ecomic.Models.RegisterViewModel
@{ViewBag.Title = "Trang đăng kí ";
    <link href="~/css/FormTaiKhoan.css" rel="stylesheet" />
    List<SelectListItem> li = new List<SelectListItem>();
    li.Add(new SelectListItem { Text = "Nam", Value = "0" });
    li.Add(new SelectListItem { Text = "Nữ", Value = "1" });
    ViewData["gioitinh"] = li;
}

<div>
    @using (Html.BeginForm("Dangki", "T2V_", FormMethod.Post, new { @class = "sign-up" }))
    {
        
        <fieldset>
            <div class="login-header">
                <span>Đăng kí</span>
                <a href="#" class="close">Close</a>
            </div>
            <div class="Error">
                @if (@Session["Loi"] != null)
                 {
                     <p>@Session["Loi"]</p>
                 }
            </div>
            <div class="login-content">
                <label for="name">Email:</label>
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
                <label for="pass">Password:</label>
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
                <label for="pass">Confirm:</label>
                @Html.PasswordFor(m => m.ConfirmPassword)
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
               @Html.LabelFor(m => m.Captcha)
                <img alt="Captcha" src="@Url.Action("CaptchaImage")" style="" />

                <div class="editor-field">
                    @Html.EditorFor(m => m.Captcha)
                    @Html.ValidationMessageFor(m => m.Captcha)
                </div>
                <input type="submit" value="Log In" class="loginsubmit" />
            </div>
        </fieldset>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

T2V_Bee/Web_ecomic/Views/T2V_/Partial_formlogin.cshtml
@model Web_ecomic.Models.LoginViewModel
@{
    ViewBag.Title = "Trang đăng nhập";
    <link href="~/css/FormTaiKhoan.css" rel="stylesheet" />
}

<div>
    @using (Html.BeginForm("Dangnhap", "T2V_", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "login1" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
            <div class="login-header">
                <span>Đăng nhập</span>
                <a href="#" class="close">Close</a>
            </div>
            <div class="Error">
                @if (@Session["Loi"] != null)
                {
                    <p>@Session["Loi"]</p>
                }
            </div>
            <div class="login-content">
                <label for="name">Email:</label>
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
                <label for="pass">Password:</label>
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
                <input type="submit" value="Log In" class="loginsubmit" />
                <div class="checkbox-inline">
                    <div>
                        @Html.CheckBoxFor(m => m.RememberMe) 
                        <i>Remember me ?</i>
                        <i><a href="@Url.Action("Quenmatkhau","T2V_")">Forget password</a></i>
                    </div>
                </div>
            </div>
        </fieldset>
    }
</div>

T2V_Bee/Web_ecomic/Views/T2V_/Quenmatkhau.cshtml
@model Web_ecomic.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Quenmatkhau";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @using (Html.BeginForm("Quenmatkhau", "T2V_", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
            <div class="row">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email)
                    @Html.ValidationMessageFor(m => m.Email)
                    <input type="submit" value=" Tìm " />
                </div>
                <div class="col-md-4">

                </div>
            </div>
        </fieldset>
    }
</div>